# Generated by Django 3.1.7 on 2021-05-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='body',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
